# Experiment No 13
## Data Binning and Data Formatting using Python
## Name: Aanjneya Pankharaj
## PRN: 25070123002
### Batch: ENTC A1

In [17]:
import pandas as pd
import numpy as np
data={
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,45000],
    'Units Sold':[25,60,35,80,50,15]
}
df=pd.DataFrame(data)
df

      Product  Price  Units Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [18]:
# Data Binning
bins=[0,10000,30000,60000]
labels=['Low','Medium','High']
df['Price Category']=pd.cut(df['Price'],bins=bins,labels=labels)
df

      Product  Price  Units Sold Price Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [19]:
# Data Binning for units sold
bins=[0,10,35,85]
labels=['Less sell','Moderate sell','High sell']
df['Sell Category']=pd.cut(df['Units Sold'],bins=bins,labels=labels)
df

      Product  Price  Units Sold Price Category  Sell Category
0      Laptop  55000          25           High  Moderate sell
1      Mobile  20000          60         Medium      High sell
2      Tablet  30000          35         Medium  Moderate sell
3  Headphones   2000          80            Low      High sell
4  Smartwatch   8000          50            Low      High sell
5      Camera  45000          15           High  Moderate sell

In [20]:
# Data Formatting
# Convert Data Type
print(df.dtypes)
df['Units Sold']=df['Price'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units Sold           int64
Price Category    category
Sell Category     category
dtype: object
Product             object
Price                int64
Units Sold         float64
Price Category    category
Sell Category     category
dtype: object

In [22]:
# Convert Text to Uppercase
df['Product']=df['Product'].str.upper()
df

      Product  Price  Units Sold Price Category  Sell Category
0      LAPTOP  55000     55000.0           High  Moderate sell
1      MOBILE  20000     20000.0         Medium      High sell
2      TABLET  30000     30000.0         Medium  Moderate sell
3  HEADPHONES   2000      2000.0            Low      High sell
4  SMARTWATCH   8000      8000.0            Low      High sell
5      CAMERA  45000     45000.0           High  Moderate sell

In [24]:
# Rounding Values
df['Price']=df['Price'].round(2)
df

      Product  Price  Units Sold Price Category  Sell Category
0      LAPTOP  55000     55000.0           High  Moderate sell
1      MOBILE  20000     20000.0         Medium      High sell
2      TABLET  30000     30000.0         Medium  Moderate sell
3  HEADPHONES   2000      2000.0            Low      High sell
4  SMARTWATCH   8000      8000.0            Low      High sell
5      CAMERA  45000     45000.0           High  Moderate sell

In [25]:
# Addtional Operations
# Sort Data
sorted_df=df.sort_values(by='Price',ascending=False)
sorted_df

      Product  Price  Units Sold Price Category  Sell Category
0      LAPTOP  55000     55000.0           High  Moderate sell
5      CAMERA  45000     45000.0           High  Moderate sell
2      TABLET  30000     30000.0         Medium  Moderate sell
1      MOBILE  20000     20000.0         Medium      High sell
4  SMARTWATCH   8000      8000.0            Low      High sell
3  HEADPHONES   2000      2000.0            Low      High sell

In [26]:
# Display Unique Values
print(df['Price Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [27]:
# DataSet:Food Delivery Orders
import pandas as pd
import numpy as np
data={
    'Order_ID':['01','02','03','04','05','06','07','08'],
    'Order_value':[250,450,120,600,300,150,500,220],
    'Delivery_time':[30,45,25,60,35,20,50,28],
    'Distance_km':[5,8,3,10,6,2,9,4]
}
df=pd.DataFrame(data)
df

  Order_ID  Order_value  Delivery_time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [29]:
# Binning Order Value
bins=[0,200,400,600]
labels=['Low','Medium','High']
df['Order_Category']=pd.cut(df['Order_value'],bins=bins,labels=labels)
df

  Order_ID  Order_value  Delivery_time  Distance_km Order_Category
0       01          250             30            5         Medium
1       02          450             45            8           High
2       03          120             25            3            Low
3       04          600             60           10           High
4       05          300             35            6         Medium
5       06          150             20            2            Low
6       07          500             50            9           High
7       08          220             28            4         Medium

In [30]:
# Binning Delivery Time
bins2=[0,30,45,75]
labels2=['Fast','Medium','Slow']
df['Delivery_Category']=pd.cut(df['Delivery_time'],bins=bins2,labels=labels2)
df

,Order_ID,Order_value,Delivery_time,Distance_km,Order_Category,Delivery_Category
0,01,250,30,5,Medium,Fast
1,02,450,45,8,High,Medium
2,03,120,25,3,Low,Fast
3,04,600,60,10,High,Slow
4,05,300,35,6,Medium,Medium
5,06,150,20,2,Low,Fast
6,07,500,50,9,High,Slow
7,08,220,28,4,Medium,Fast

In [31]:
# Data Formatting Examples
#Convert Distance To Float
df['Distance_km']=df['Distance_km'].astype(float)
df

,Order_ID,Order_value,Delivery_time,Distance_km,Order_Category,Delivery_Category
0,01,250,30,5.0,Medium,Fast
1,02,450,45,8.0,High,Medium
2,03,120,25,3.0,Low,Fast
3,04,600,60,10.0,High,Slow
4,05,300,35,6.0,Medium,Medium
5,06,150,20,2.0,Low,Fast
6,07,500,50,9.0,High,Slow
7,08,220,28,4.0,Medium,Fast

In [32]:
# Convert Order_Category to uppercase
df['Order_Category']=df['Order_Category'].str.upper()
df

,Order_ID,Order_value,Delivery_time,Distance_km,Order_Category,Delivery_Category
0,01,250,30,5.0,MEDIUM,Fast
1,02,450,45,8.0,HIGH,Medium
2,03,120,25,3.0,LOW,Fast
3,04,600,60,10.0,HIGH,Slow
4,05,300,35,6.0,MEDIUM,Medium
5,06,150,20,2.0,LOW,Fast
6,07,500,50,9.0,HIGH,Slow
7,08,220,28,4.0,MEDIUM,Fast

In [33]:
# Unique categories
print(df['Order_Category'].unique())
df

['MEDIUM' 'HIGH' 'LOW']

,Order_ID,Order_value,Delivery_time,Distance_km,Order_Category,Delivery_Category
0,01,250,30,5.0,MEDIUM,Fast
1,02,450,45,8.0,HIGH,Medium
2,03,120,25,3.0,LOW,Fast
3,04,600,60,10.0,HIGH,Slow
4,05,300,35,6.0,MEDIUM,Medium
5,06,150,20,2.0,LOW,Fast
6,07,500,50,9.0,HIGH,Slow
7,08,220,28,4.0,MEDIUM,Fast

In [35]:
# Count of Categories
print(df['Order_Category'].value_counts())
df

Order_Category
MEDIUM    3
HIGH      3
LOW       2
Name: count, dtype: int64

,Order_ID,Order_value,Delivery_time,Distance_km,Order_Category,Delivery_Category
0,01,250,30,5.0,MEDIUM,Fast
1,02,450,45,8.0,HIGH,Medium
2,03,120,25,3.0,LOW,Fast
3,04,600,60,10.0,HIGH,Slow
4,05,300,35,6.0,MEDIUM,Medium
5,06,150,20,2.0,LOW,Fast
6,07,500,50,9.0,HIGH,Slow
7,08,220,28,4.0,MEDIUM,Fast

In [36]:
# Sorting
print(df.sort_values(by='Order_value'))
df

  Order_ID  Order_value  Delivery_time  Distance_km Order_Category  \
2       03          120             25          3.0            LOW
5       06          150             20          2.0            LOW
7       08          220             28          4.0         MEDIUM
0       01          250             30          5.0         MEDIUM
4       05          300             35          6.0         MEDIUM
1       02          450             45          8.0           HIGH
6       07          500             50          9.0           HIGH
3       04          600             60         10.0           HIGH

  Delivery_Category
2              Fast
5              Fast
7              Fast
0              Fast
4            Medium
1            Medium
6              Slow
3              Slow

,Order_ID,Order_value,Delivery_time,Distance_km,Order_Category,Delivery_Category
0,01,250,30,5.0,MEDIUM,Fast
1,02,450,45,8.0,HIGH,Medium
2,03,120,25,3.0,LOW,Fast
3,04,600,60,10.0,HIGH,Slow
4,05,300,35,6.0,MEDIUM,Medium
5,06,150,20,2.0,LOW,Fast
6,07,500,50,9.0,HIGH,Slow
7,08,220,28,4.0,MEDIUM,Fast